# Generated by Django 5.0.6 on 2024-06-02 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
