# Generated by Django 5.0.6 on 2024-06-02 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_delete_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100, null=True)),
                ('teacher_lastname', models.CharField(max_length=100, null=True)),
                ('teacher_gender', models.CharField(max_length=100, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.classroom')),
            ],
        ),
    ]
