# Generated by Django 5.0.6 on 2024-06-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='apis.classroom'),
        ),
    ]
