# Generated by Django 5.0.6 on 2024-06-03 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_alter_teacher_classrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='school',
        ),
        migrations.AddField(
            model_name='classroom',
            name='classroom_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.school'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.school'),
        ),
    ]
