# Generated by Django 5.0.6 on 2024-06-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100, null=True)),
                ('school_Abbreviate_name', models.CharField(max_length=100, null=True)),
                ('school_address', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
